language: ruby
rvm:
  - 2.2.2

before_script:
  - bundle install
  # install gcloud
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; source /home/travis/google-cloud-sdk/path.bash.inc
  # decrypt and activate credentials
  - if [ ! -z $encrypted_1777d5e47dd8_key ]; then
      openssl aes-256-cbc -K $encrypted_1777d5e47dd8_key -iv $encrypted_1777d5e47dd8_iv -in credentials.json.enc -out credentials.json -d
    fi
  - gcloud auth activate-service-account --key-file=credentials.json

script:
  - bash ./build.sh

env:
  global:
  - GH_REF: github.com/bshaffer/oauth2-server-php-docs.git
  - GOOGLE_APPLICATION_CREDENTIALS: $TRAVIS_BUILD_DIR/credentials.json
  - secure: RmCrtGWhma7O3Q7rzeVgEskwUA5GKMjkRp4/2qrLbNr1Ug1/bUV/OeDn5gUk+UFijRbDzeNWGxx0LNM4Cv1Cmp3FEpizzosy35bzIwSu3aBQ97sKRbgpQJ09g5PbflqxGVc3nUTPwSPNIeAxNUED9HAlq5kQ0IBCo6qEItHU+R4=
